--DROP TABLE mydb.offers;
-- CREATE TABLE mydb.offers (
-- id  INT PRIMARY KEY NOT NULL,
-- name TEXT NOT NULL,
-- email TEXT NOT NULL,
-- text TEXT NOT NULL
-- );
--INSERT INTO mydb.offers VALUES (1,'Bob','bob@nowhereatall.com','I will write Java for you'),(2,'Mike','mike@nowhereatall.com','Web design, very cheap'),(3,'Sue','sue@nowhereatall.com','PHP coding');
--SELECT * FROM mydb.offers;